[package]
authors = ["Pavel Ivanov <mr.pavel.ivanov@gmail.com>"]
categories = ["command-line-utilities"]
description = "Utility for viewing json-formatted log files."
keywords = ["cli", "human", "log"]
name = "hl"
version = "0.7.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
atoi = "0.3.2"
bitmask = "0.5"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
closure = "0.3"
error-chain = "0.12"
flate2 = "1.0"
heapless = "0.5.5"
itertools = "0.9"
crossbeam-utils = "0.7"
crossbeam-queue = "0.2"
crossbeam-channel = "0.4"
isatty = "0.1"
num_cpus = "1.0"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
shellwords = "1.1"
signal-hook = "0.1"

[dependencies.itoa]
version = "0.4.3"
default-features = false

[dev-dependencies]
criterion = "0.3"
diligent-date-parser = "0.1"
regex = "1"

[profile.release]
debug = false
opt-level = 3
codegen-units = 1
lto = true

[[bench]]
name = "ts_parse"
harness = false

[[bench]]
name = "ts_format"
harness = false
